name: Update Demo Shoots

on:
  schedule:
    - cron: '32 2 * * 3'
  workflow_dispatch:

jobs:
  execute-script:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2
      
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'
      
    - name: Install dependencies
      run: npm install
      
    - name: Run the script
      run: node ./app.js
      env:
        SHOOTS: ${{ secrets.SHOOTS }}
        DB_STRING: ${{ secrets.DB_STRING }}
